#!/bin/bash

# TODO -- Use relative paths instead of absolute :)

PYENV=/home/victor/coding/tools/mavlink/env
MAVGEN=/home/victor/coding/tools/mavlink/pymavlink/tools/mavgen.py

PROJECT_BASE=/home/victor/projects/asac-fc
OUTPUT_C=${PROJECT_BASE}/include/mavlink
OUTPUT_PYTHON=${PROJECT_BASE}/tools/mavlink-client/mavlink
#INPUT=${PROJECT_BASE}/tools/mavlink-client/message_definitions/v1.0/asac.xml
INPUT=${PROJECT_BASE}/tools/mavlink-client/message_definitions/v1.0/common.xml


# Arguments:
#   $1 - Lang
#   $2 - Output dir
generate_mavlink() {
    LANG=$1
    OUTPUT_DIR=$2

    source ${PYENV}/bin/activate && \
        python ${MAVGEN}            \
            --lang=$LANG            \
            --wire-protocol=1.0     \
            --output=${OUTPUT_DIR}  \
            ${INPUT}
}

generate_mavlink C ${OUTPUT_C}

generate_mavlink Python3 ${OUTPUT_PYTHON}

