M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date ons  7 jun 2023 20:54:12
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-07T20:54:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0315
%
G90
G05
T1
X4.371Y-4.5106
X4.371Y-4.7382
T2
X5.5547Y-4.5878
X5.5547Y-4.6547
T0
M30
